# Generated by Django 4.0.4 on 2022-05-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='아이디')),
                ('user_pw', models.CharField(max_length=100, verbose_name='비밀번호')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True, verbose_name='닉네임')),
                ('user_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
                'db_table': 'accounts',
                'managed': True,
            },
        ),
    ]
