# Generated by Django 4.0.4 on 2022-05-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslist',
            name='lede',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='짧은 내용'),
        ),
    ]
