# Generated by Django 4.0.4 on 2022-05-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_newslist_time1_newslist_time2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslist',
            name='rg_date',
            field=models.DateTimeField(auto_now=True, verbose_name='등록일'),
        ),
    ]
