# Generated by Django 4.0.4 on 2022-06-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_newslist_writing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslist',
            name='rg_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
    ]
